### ISSUE TITLE
Required libraries

### ISSUE THREAD

**Issue by daydreamandy** [mohitbhoite/cumin-lander#1]
I have installed the required libraries as per the links in the readme file.
I still have errors with:
#include <bluefruit.h>
#include <Adafruit_LittleFS.h>
#include <InternalFileSystem.h>

Are these file names correct?

**Comment by mohitbhoite** [comment]
Looks like you'll need to install [Arduino BSP for Adafruit Bluefruit nRF52 series](https://github.com/adafruit/Adafruit_nRF52_Arduino/tree/master) first. I have updated the readme accordingly. Let me know if this works for you!

**Comment by daydreamandy** [comment]
Thanks for the help, clicked your new link, downloaded as zip. installed library as zip in arduino:
"Specified folder/zip file does not contain a valid library"

**Comment by daydreamandy** [comment]
All sorted. I had the wrong Seeed board selected.
Breadboard version working very well. Thanks!

**Comment by mohitbhoite** [comment]
Yaay!
